<div class="site-footer">
    <div class="safebuy">
        <div class="view">
            <img src="./images/safebuy.jpg">
        </div>
    </div>
    <div class="view">
        <div class="f-guide">
            <div class="tit"><span class="iconfont icon-guidepost"></span>新手指南</div>
            <ul class="ullist">
                <li><a href="#">购物流程</a></li>
                <li><a href="#">会员政策</a></li>
                <li><a href="#">联系客服</a></li>
                <li><a href="#">积分政策</a></li>
                <li><a href="#">加入我们</a></li>
            </ul>
        </div>
        <div class="f-guide">
            <div class="tit"><span class="iconfont icon-peisong"></span>配送方式</div>
            <ul class="ullist">
                <li><a href="#">配送时效</a></li>
                <li><a href="#">配送范围</a></li>
                <li><a href="#">配送收费标准</a></li>
                <li><a href="#">关于我们</a></li>
            </ul>
        </div>
        <div class="f-guide">
            <div class="tit"><span class="iconfont icon-zhifufangshi"></span>支付方式</div>
            <ul class="ullist">
                <li><a href="#">在线支付</a></li>
                <li><a href="#">其他支付方式</a></li>
                <li><a href="#">优惠券使用</a></li>
                <li><a href="#">礼金卡使用</a></li>
            </ul>
        </div>
        <div class="f-guide">
            <div class="tit"><span class="iconfont icon-shouhou"></span>售后服务</div>
            <ul class="ullist">
                <li><a href="#">验收与拒收政策</a></li>
                <li><a href="#">退换货政策</a></li>
                <li><a href="#">退换货流程</a></li>
                <li><a href="#">退款流程</a></li>
                <li><a href="#">发票制度</a></li>
            </ul>
        </div>
        <div class="weixin">
            <img src="./images/weixin.jpg" alt="">
        </div>
        <div class="clearfix"></div>
        <p class="icp">© 2017 农产品专卖网 版权所有，并保留所有权利。联系地址:遂宁市船山区中国西部现代物流港物流大道488号 ICP备案证书号:蜀ICP备1001号</p>
        <div class="renzhen">
            <a href="#" class="cxwz"></a>
            <a href="#" class="zfb"></a>
            <a href="#" class="gjjxxh"></a>
            <a href="#" class="u1"></a>
            <a href="#" class="gs"></a>
            <a href="#" class="wljc"></a>
        </div>
    </div>
</div>