<div class="header">
    <div class="view">
        <span class="iconfont icon-homeshape"></span> 当前城市：
        <div class="area">
            <span>成都 <span class="iconfont icon-xiangxiazhankai"></span></span>
            <div class="choisecity">
                <span class="iconfont icon-close"></span>
                <div>您当前所选城市为：<span class="b">成都</span></div>
                <div class="lh20">
                    <div class="hotcity">
                        热门城市：
                    </div>
                    <div class="hotcitylist">
                        <span class="item">北京</span>
                        <span class="item">上海</span>
                        <span class="item">广州</span>
                        <span class="item">武汉</span>
                        <span class="item">沈阳</span>
                        <span class="item">郑州</span>
                        <span class="item">南京</span>
                        <span class="item">成都</span>
                        <span class="item">福州</span>
                        <span class="item">天津</span>
                        <span class="item">深圳</span>
                        <span class="item">杭州</span>
                        <span class="item">苏州</span>
                        <span class="item">无锡</span>
                        <span class="item">青岛</span>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="mchoise active">请选择省<span class="dsj"></span></div>
                <!--<div class="mchoise ">请选择市<span class="dsj"></span></div>-->
                <!--<div class="mchoise ">请选择区<span class="dsj"></span></div>-->
                <div class="mchoise-list">
                    <div>
                        <div class="hcity">A-G</div>
                        <div class="hcity-list">
                            <span class="item">安徽</span>
                            <span class="item">北京</span>
                            <span class="item">重庆</span>
                            <span class="item">福建</span>
                            <span class="item">广西</span>
                            <span class="item">贵州</span>
                            <span class="item">广州</span>
                            <span class="item">甘肃</span>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div>
                        <div class="hcity">H-K</div>
                        <div class="hcity-list">
                            <span class="item">湖南</span>
                            <span class="item">海南</span>
                            <span class="item">河北</span>
                            <span class="item">黑龙江</span>
                            <span class="item">湖北</span>
                            <span class="item">河南</span>
                            <span class="item">江苏</span>
                            <span class="item">吉林</span>
                            <span class="item">江西</span>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div>
                        <div class="hcity">L-S</div>
                        <div class="hcity-list">
                            <span class="item">辽宁</span>
                            <span class="item">内蒙古</span>
                            <span class="item">宁夏</span>
                            <span class="item">青海</span>
                            <span class="item">上海</span>
                            <span class="item">山东</span>
                            <span class="item">山西</span>
                            <span class="item">陕西</span>
                            <span class="item">四川</span>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div>
                        <div class="hcity">T-Z</div>
                        <div class="hcity-list">
                            <span class="item">天津</span>
                            <span class="item">新疆</span>
                            <span class="item">云南</span>
                            <span class="item">浙江</span>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
            <div class="bbline"></div>
        </div>
        欢迎来到农产品专卖网！
        <div class="navlist">
            <a href="#">[请登录]</a>
            <a href="#">[免费注册]</a>
            <span class="d">|</span>
            <a href="#">我的订单</a>
            <span class="d">|</span>
            <a href="#">会员俱乐部</a>
            <span class="d">|</span>
            <a href="#">微信扫码</a>
            <span class="d">|</span>
            <a href="#">客户服务</a>
            <span class="d">|</span>
            <a href="#">网站导航</a>
        </div>
    </div>
</div>
<div class="view top-wrap">
    <img src="./images/logo.png" alt="" class="logo">
    <div class="search-box">
        <img src="./images/search-icon_1.png" alt="" class="iconflower">
        <div class="search-ctn">
            <span class="type">全部<span class="dsj"></span></span>
            <input type="text" class="search-bar">
            <input type="submit" value="搜索" class="submit">
            <div class="clear"></div>
        </div>
        <div class="hot">
            大家都在搜：
            <a href="#">大枣</a><span class="d">|</span>
            <a href="#">野生菌</a><span class="d">|</span>
            <a href="#">蜂蜜</a><span class="d">|</span>
            <a href="#">普洱茶</a>
        </div>
    </div>
    <div class="sidenav">
        <a href="#" class="item">
            <span class="iconfont icon-jiatingnongchang"></span>
            <span class="txt">特色小镇</span>
        </a>
        <a href="#" class="item">
            <span class="iconfont icon-haonongchangb"></span>
            <span class="txt">开心农场</span>
        </a>
        <a href="#" class="item">
            <span class="iconfont icon-law"></span>
            <span class="txt">扶贫政策</span>
        </a>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>
<div class="mainnav">
    <div class="view">
        <img src="./images/navall.png" class="allnavicon"/>
        <ul class="navul">
            <li class="all navul-li">全部商品详细分类
                <ul class="nav-total">
                    <li class="nav-total-li">
                        <div class="title"><span class="iconfont icon-liangyoufushi"></span>粮油米面<span
                                class="iconfont icon-xiayiyeqianjinchakangengduo"></span></div>
                        <div class="hot"><a href="#">大米</a> <a href="#">糯米</a> <a href="#">薏米</a> <a href="#">荞面</a> <a
                                href="#">小米</a></div>
                        <div class="li-detail">
                            <div class="hidelborder"></div>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                        </div>
                    </li>
                    <li class="nav-total-li">
                        <div class="title"><span class="iconfont icon-yingtao"></span>粮油米面<span
                                class="iconfont icon-xiayiyeqianjinchakangengduo"></span></div>
                        <div class="hot"><a href="#">大米</a> <a href="#">糯米</a> <a href="#">薏米</a> <a href="#">荞面</a> <a
                                href="#">小米</a></div>
                        <div class="li-detail l2">
                            <div class="hidelborder"></div>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                        </div>
                    </li>
                    <li class="nav-total-li">
                        <div class="title"><span class="iconfont icon-paw"></span>粮油米面<span
                                class="iconfont icon-xiayiyeqianjinchakangengduo"></span></div>
                        <div class="hot"><a href="#">大米</a> <a href="#">糯米</a> <a href="#">薏米</a> <a href="#">荞面</a> <a
                                href="#">小米</a></div>
                        <div class="li-detail l3">
                            <div class="hidelborder"></div>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                        </div>
                    </li>
                    <li class="nav-total-li">
                        <div class="title"><span class="iconfont icon-jidanyijindayue"></span>粮油米面<span
                                class="iconfont icon-xiayiyeqianjinchakangengduo"></span></div>
                        <div class="hot"><a href="#">大米</a> <a href="#">糯米</a> <a href="#">薏米</a> <a href="#">荞面</a> <a
                                href="#">小米</a></div>
                        <div class="li-detail l4">
                            <div class="hidelborder"></div>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                        </div>
                    </li>
                    <li class="nav-total-li">
                        <div class="title"><span class="iconfont icon-xianhua"></span>粮油米面<span
                                class="iconfont icon-xiayiyeqianjinchakangengduo"></span></div>
                        <div class="hot"><a href="#">大米</a> <a href="#">糯米</a> <a href="#">薏米</a> <a href="#">荞面</a> <a
                                href="#">小米</a></div>
                        <div class="li-detail l5">
                            <div class="hidelborder"></div>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                        </div>
                    </li>
                    <li class="nav-total-li">
                        <div class="title"><span class="iconfont icon-nongji"></span>粮油米面<span
                                class="iconfont icon-xiayiyeqianjinchakangengduo"></span></div>
                        <div class="hot"><a href="#">大米</a> <a href="#">糯米</a> <a href="#">薏米</a> <a href="#">荞面</a> <a
                                href="#">小米</a></div>
                        <div class="li-detail l6">
                            <div class="hidelborder"></div>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                        </div>
                    </li>
                    <li class="nav-total-li">
                        <div class="title"><span class="iconfont icon-qita"></span>粮油米面<span
                                class="iconfont icon-xiayiyeqianjinchakangengduo"></span></div>
                        <div class="hot"><a href="#">大米</a> <a href="#">糯米</a> <a href="#">薏米</a> <a href="#">荞面</a> <a
                                href="#">小米</a></div>
                        <div class="li-detail l7">
                            <div class="hidelborder"></div>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                            <dl class="typelist">
                                <dt class="type">热门推荐</dt>
                                <dd class="itemlist">
                                    <a href="#" class="item">煲汤佳配</a>
                                    <a href="#" class="item">橄榄油</a>
                                    <a href="#" class="item">李玉双大米</a>
                                    <a href="#" class="item">泰国香米</a>
                                    <a href="#" class="item">五常稻花香</a>
                                    <a href="#" class="item">有机粮油</a>
                                    <a href="#" class="item">滋补养生</a>
                                </dd>
                            </dl>
                        </div>
                    </li>
                </ul>
            </li>
            <li class="navul-li"><a href="#">首页</a></li>
            <li class="navul-li"><a href="#">绿色有机</a></li>
            <li class="navul-li"><a href="#">地标产品</a></li>
            <li class="navul-li active"><a href="#">非遗产品</a></li>
            <li class="navul-li"><a href="#">扶贫专区</a></li>
            <li class="navul-li"><a href="#">商家</a></li>
            <li class="navul-li"><a href="#">商城</a></li>
            <li class="navul-li"><a href="#">供求</a></li>
            <li class="navul-li"><a href="#">资讯</a></li>
            <li class="navul-li"><a href="#">农商物流</a></li>
            <li class="navul-li"><a href="#">农商金融</a></li>
            <div class="clearfix"></div>
        </ul>
    </div>
</div>
