<div class="nav-u-left scenter">
    <div class="ntitle"><span class="iconfont">&#xe60b;</span>商品管理</div>
    <div class="list">
        <div class="c"><a href="#">商品发布</a></div>
        <div class="c"><a href="#">在售商品</a></div>
        <div class="c"><a href="#">未上架商品</a></div>
        <div class="c"><a href="#">批量发售</a></div>
    </div>
    <div class="ntitle"><span class="iconfont">&#xe60b;</span>交易管理</div>
    <div class="list">
        <div class="c"><a href="#">已卖出的商品</a></div>
        <div class="c"><a href="#">交易评价管理</a></div>
        <div class="c"><a href="#">我收到的退款</a></div>
        <div class="c"><a href="#">投诉管理</a></div>
    </div>
    <div class="ntitle"><span class="iconfont">&#xe60b;</span>商铺管理</div>
    <div class="list">
        <div class="c"><a href="#">图片中心</a></div>
        <div class="c"><a href="#">商铺产品分类</a></div>
        <div class="c"><a href="#">产品推荐</a></div>
        <div class="c"><a href="#">商铺装修</a></div>
    </div>
    <div class="ntitle"><span class="iconfont">&#xe60b;</span>客服助手</div>
    <div class="list">
        <div class="c"><a href="#">QQ客服</a></div>
        <div class="c"><a href="#">微信客服</a></div>
        <div class="c"><a href="#">400电话</a></div>
        <div class="c"><a href="#">注销账号</a></div>
    </div>
    <div class="ntitle"><span class="iconfont">&#xe60b;</span>经营助手</div>
    <div class="list">
        <div class="c"><a href="#">留言管理</a></div>
        <div class="c"><a href="#">访客分析</a></div>
        <div class="c"><a href="#">物流运费设置</a></div>
        <div class="c"><a href="#">物流发货</a></div>
    </div>
</div>